# uncomment for Linux
#CC = gcc
#CO = gcc -m32
#FORMAT = elf32
#RM = rm -f

# uncomment for Mac OS X
#CC = gcc
#CO = gcc -m32 -fno-pie
#FORMAT = macho32
#RM = rm -f

# uncomment for Windows (make sure MinGW/MSYS are installed!)
#CC = c:\mingw\bin\gcc
#CO = $(CC)
#FORMAT = win32
#RM = del # cmd.exe
#RM = rm -fo # PowerShell

c_program.exe: ex5b.c
	$(CC) ex5b.c -o c_program.exe

asm_program.exe: ex5b.obj
	$(CO) ex5b.obj -o asm_program.exe

ex5b.obj: ex5b.asm
	nasm -f $(FORMAT) ex5b.asm -o ex5b.obj

clean:
	$(RM) *.obj

cleanall: clean
	$(RM) *.exe
