IEEE (Institute of Electrical and Electronics Engineers) 754
  +http://class.ece.iastate.edu/arun/Cpre305/ieee754/ie4.html
  +https://www.h-schmidt.net/FloatConverter/IEEE754.html
  +Floating point values in binary
  +32-bit, 64-bit

 _  _ _ _ _ _ _ _ _ _   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 ^sign    ^exponent       ^mantissa
 "1." mystery bit
0 01111011 manitssa = .2 0010100001________________________
 .075/2^? = 1._________     1) exp
 .075/2^4 = 1.2             2) bias: -4 + [127] <- standard
                            3) exp: 123
