# uncomment for Linux
#CC = gcc
#CO = gcc -m32
#FORMAT = elf32
#RM = rm -f

# uncomment for Mac OS X
#CC = gcc
#CO = gcc -m32 -fno-pie
#FORMAT = macho32
#RM = rm -f

# uncomment for Windows (make sure MinGW/MSYS are installed!)
#CC = c:\mingw\bin\gcc
#CO = $(CC)
#FORMAT = win32
#RM = del # cmd.exe
#RM = rm -fo # PowerShell

asm_program.exe: ex6b.obj
	$(CO) ex6b.obj -o asm_program.exe

ex6b.obj: ex6b.asm
	nasm -f $(FORMAT) ex6b.asm -o ex6b.obj

clean:
	$(RM) *.obj

cleanall: clean
	$(RM) *.exe
